models:

  core.model:
    properties:
      name:
        field:
          type: core.property.field.string
      parent:
        relationship:
          type:     core.property.relationship.toOne
          target:   core.model
      properties:
        relationship:
          type:     core.property.relationship.toMany
          target:   core.property
      extensions:
        relationship:
          type: core.property.relationship.toMany
          target: core.extension.model
      abstract:
        field:
          type: core.property.field.boolean
      toString:
        field:
          type: core.property.field.string

  core.property:
    properties:
      name:
        field:
          type: core.property.field.string
      extensions:
        relationship:
          type: core.property.relationship.toMany
          target: core.extension.property
  core.property.field:
    parent: core.property
    properties:
      defaultValue:
        field:
          type: core.property.field.mixed
  core.property.field.boolean:
    parent: core.property.field
  core.property.field.datetime:
    parent: core.property.field
  core.property.field.file:
    parent: core.property.field
  core.property.field.float:
    parent: core.property.field
  core.property.field.integer:
    parent: core.property.field
  core.property.field.markdown:
    parent: core.property.field
  core.property.field.mixed:
    parent: core.property.field
  core.property.field.string:
    parent: core.property.field
  core.property.field.text:
    parent: core.property.field

  core.property.relationship:
    parent: core.property
    properties:
      target:
        relationship:
          type:     core.property.relationship.toOne
          target:   core.model
  core.property.relationship.toMany:
    parent: core.property.relationship
  core.property.relationship.toOne:
    parent: core.property.relationship

  core.property.classType:
    parent: core.property
    properties:
      className:
        field:
          type: core.property.field.string

  core.property.collection:
    parent: core.property
    properties:
      className:
        field:
          type: core.property.field.string

  core.extension.model: []
  core.extension.property: []
  core.extension.property.computed:
    parent: core.extension.property