models:

  core.model:
    toString: name
    properties:
      name:
        field:
          type: core.property.field.string_type
      parent:
        relationship:
          type: core.property.relationship.toOne
          target: core.model
      properties:
        relationship:
          type: core.property.relationship.toMany
          target: core.property
      extensions:
        relationship:
          type: core.property.relationship.toMany
          target: core.extension.model
      abstract:
        field:
          type: core.property.field.boolean_type
          defaultValue: false
      toString:
        field:
          type: core.property.field.string_type

  core.property:
    properties:
      name:
        field:
          type: core.property.field.string_type
      readOnly:
        field:
          type: core.property.field.boolean_type
          defaultValue: false
      calculated:
        field:
          type: core.property.field.string_type
      extensions:
        relationship:
          type: core.property.relationship.toMany
          target: core.extension.property

  core.property.field:
    parent: core.property
    properties:
      internalType:
        field:
          type: core.property.field.string_type
          readOnly: true
      defaultValue:
        field:
          type: core.property.field.mixed_type

  core.property.field.boolean_type:
    parent: core.property.field
    properties:
      internalType:
        field:
          type: core.property.field.string_type
          defaultValue: boolean
          readOnly: true
  core.property.field.date_type:
    parent: core.property.field
    properties:
      internalType:
        field:
          type: core.property.field.string_type
          defaultValue: '\DateTime'
          readOnly: true
  core.property.field.datetime_type:
    parent: core.property.field
    properties:
      internalType:
        field:
          type: core.property.field.string_type
          defaultValue: '\DateTime'
          readOnly: true
  core.property.field.file_type:
    parent: core.property.field
  core.property.field.float_type:
    parent: core.property.field
    properties:
      internalType:
        field:
          type: core.property.field.string_type
          defaultValue: float
          readOnly: true
  core.property.field.integer_type:
    parent: core.property.field
    properties:
      internalType:
        field:
          type: core.property.field.string_type
          defaultValue: integer
          readOnly: true
  core.property.field.markdown_type:
    parent: core.property.field
    properties:
      internalType:
        field:
          type: core.property.field.string_type
          defaultValue: string
          readOnly: true
  core.property.field.mixed_type:
    parent: core.property.field
  core.property.field.string_type:
    parent: core.property.field
    properties:
      internalType:
        field:
          type: core.property.field.string_type
          defaultValue: string
          readOnly: true
  core.property.field.text_type:
    parent: core.property.field
    properties:
      internalType:
        field:
          type: core.property.field.string_type
          defaultValue: string
          readOnly: true

  core.property.relationship:
    parent: core.property
    properties:
      target:
        relationship:
          type: core.property.relationship.toOne
          target: core.model
      composition:
        field:
          type: core.property.field.boolean_type
          defaultValue: false
  core.property.relationship.toMany:
    parent: core.property.relationship
  core.property.relationship.toOne:
    parent: core.property.relationship

  core.property.collection:
    parent: core.property
    properties:
      className:
        field:
          type: core.property.field.string_type

  core.extension.model: []
  core.extension.property: []
