services:

    app_gear.core.model.manager:
        class: AppGear\CoreBundle\Model\ModelManager
        arguments:
          - '%app_gear.core.model.manager.models%'
          - '@app_gear.core.tagged_manager'
          - '@service_container'
          - '%kernel.bundles%'

    app_gear.core.model.generator.source:
        class: AppGear\CoreBundle\Model\Generator\SourceGenerator
        arguments:
          - '@app_gear.core.model.manager'
          - '@event_dispatcher'
          - '%kernel.bundles%'

    app_gear.core.tagged_manager:
        class: AppGear\CoreBundle\DependencyInjection\TaggedManager
        arguments:
          - '@service_container'